Repository TeenBiscuits/Pro2324, pull requests merged in 2024-03, with the labels that each got.

#95 Nuevo Exportar a PDF
  .idea/runConfigurations/Export_to_PDF.xml
  .idea/runConfigurations/Exportar_a_PDF.xml
Labels: documentación

#101 Mas ejercicios para el Boletín 4
  docs/code/Boletin_4/Ejercicio_08.c
  docs/code/Boletin_4/Ejercicio_11.c
  docs/code/Boletin_4/Ejercicio_27.c
  docs/code/Boletin_4/Ejercicio_28.c
  docs/code/Boletin_4/Ejercicio_36.c
  docs/code/Boletin_4/Ejercicio_37.c
  docs/code/Boletin_4/Ejercicio_40.c
  src/Boletin_4/CMakeLists.txt
  src/Boletin_4/Ejercicio_08.c
  src/Boletin_4/Ejercicio_11.c
  src/Boletin_4/Ejercicio_27.c
  src/Boletin_4/Ejercicio_28.c
  src/Boletin_4/Ejercicio_36.c
  src/Boletin_4/Ejercicio_37.c
  src/Boletin_4/Ejercicio_40.c
Labels: código

#103 Nuevos Ejercicios Pro 1 Bol 4
  docs/code/Boletin_4/Ejercicio_01.c
  docs/code/Boletin_4/Ejercicio_02.c
  docs/code/Boletin_4/Ejercicio_03.c
  docs/code/Boletin_4/Ejercicio_04.c
  docs/code/Boletin_4/Ejercicio_10.c
  docs/code/Boletin_4/Ejercicio_24.c
  docs/code/Boletin_4/Ejercicio_25.c
  docs/topics/02-Boletines/Pro-1/Boletin-4.md
  src/Boletin_4/Ejercicio_01.c
  src/Boletin_4/Ejercicio_02.c
  src/Boletin_4/Ejercicio_03.c
  src/Boletin_4/Ejercicio_04.c
  src/Boletin_4/Ejercicio_10.c
  src/Boletin_4/Ejercicio_24.c
  src/Boletin_4/Ejercicio_25.c
Labels: documentación

#104 Añadidas redirecciones de la página web para evitar crear enlaces rotos
  docs/pro.tree
Labels: bug

#106 Engadir exercicios 29-31 e 33-36
  docs/code/Boletin_3/Ejercicio_29.c
  docs/code/Boletin_3/Ejercicio_30.c
  docs/code/Boletin_3/Ejercicio_31.c
  docs/code/Boletin_3/Ejercicio_33.c
  docs/code/Boletin_3/Ejercicio_34.c
  docs/code/Boletin_3/Ejercicio_35.c
  docs/code/Boletin_3/Ejercicio_36.c
  docs/topics/02-Boletines/Pro-1/Boletin-3.md
  src/Boletin_3/CMakeLists.txt
  src/Boletin_3/Ejercicio_29.c
  src/Boletin_3/Ejercicio_30.c
  src/Boletin_3/Ejercicio_31.c
  src/Boletin_3/Ejercicio_33.c
  src/Boletin_3/Ejercicio_34.c
  src/Boletin_3/Ejercicio_35.c
  src/Boletin_3/Ejercicio_36.c
Labels: código

#108 Añadir PDFs de Programación 1 y 2
  .reuse/dep5
  PDFs/Pro-1.license
  PDFs/Pro-1/Bloque1_Teoria.pdf
  PDFs/Pro-1/Bloque2_Teoria.pdf
  PDFs/Pro-1/Bloque3_Teoria.pdf
  PDFs/Pro-1/Bloque4_Teoria.pdf
  PDFs/Pro-1/Boletín1.pdf
  PDFs/Pro-1/Boletín2.pdf
  PDFs/Pro-1/Boletín3.pdf
  PDFs/Pro-1/Boletín4.pdf
  PDFs/Pro-2.license
  PDFs/Pro-2/Tema1_TAD.pdf
  PDFs/Pro-2/Tema2_GestionDinamicaMemoria.pdf
  PDFs/Pro-2/Tema2_UsoDePunteros.pdf
  PDFs/Pro-2/Tema3_Listas.pdf
Labels: documentación, mejora

#109 Eliminada versión documentación
  .github/workflows/deploy.yml
  .github/workflows/tests.yml
  .idea/runConfigurations/Construir_Documentación__pro_.xml
  SECURITY.md
  docs/cfg/buildprofiles.xml
  docs/pro.tree
  docs/writerside.cfg
Labels: bug, documentación

#112 Modificaciones para mejorar el SEO
  docs/cfg/buildprofiles.xml
  docs/cfg/gtag.js
Labels: documentación, mejora
